### ISSUE TITLE
Error in get_all_comments()

### ISSUE THREAD

**Issue by Coding-Cactus** [mat-1/repl-talk-api#6]
I have the code:
```python
import repltalk, asyncio

client = repltalk.Client()

async def getComments():
	for comment in await client.get_all_comments(order='new'):
		print(comment)

print(asyncio.run(getComments()))
```
And when i run it, I get the error:
```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    print(asyncio.run(getComments()))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 6, in getComments
    for comment in await client.get_all_comments(order='new'):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/repltalk/__init__.py", line 1232
, in get_all_comments
    for c in _comments['items']:
TypeError: list indices must be integers or slices, not str
```

I don't know if I am just doing it wrong or it is an error on your end. Can you have a look please.

**Comment by firefish111** [comment]
It might be an error due to the fact that it's out of date, but the problem might be [here](http://repl.it/graphql)

**Comment by mat-1** [comment]
repl.it removed the graphql thing for looking through all the comments :(
